---
site_name: Parallel Virtual Cluster documentation
theme:
  name: readthedocs
  titles_only: yes
  logo: "images/pvc_logo_black_transparent.png"
  width: "100%"
markdown_extensions:
  - toc:
      permalink: yes
      toc_depth: '1-4'
nav:
  - 'Home': 'index.md'
  - 'About PVC': 'about-pvc.md'
  - 'Architecture':
    - 'Cluster Architecture': 'architecture/cluster-architecture.md'
    - 'Hardware Requirements': 'architecture/hardware-requirements.md'
    - 'Fencing': 'architecture/fencing.md'
    - 'Georedundancy': 'architecture/georedundancy.md'
  - 'Deployment':
    - 'Getting Started Guide': 'deployment/getting-started.md'
  - 'Manuals':
    - 'PVC CLI': 'manuals/cli.md'
    - 'PVC HTTP API': 'manuals/api.md'
    - 'PVC Node Daemon': 'manuals/daemon.md'
    - 'PVC Provisioner': 'manuals/provisioner.md'
    - 'PVC Node Health Plugins': 'manuals/health-plugins.md'
  - 'API Reference'
    - 'PVC HTTP API': 'manuals/api-reference.html'
